//////////////////////////////////////////////////////////
/////////////////Import all images////////////////////////
//////////////////////////////////////////////////////////
import appleImg from "./Images/apple.png"
import booksImg from "./Images/books.png"
import catImg from "./Images/cat.png"
import dogImg from "./Images/dog.png"
import eggsImg from "./Images/eggs.png"
import flowerImg from "./Images/flower.png"
import giftImg from "./Images/gift.png"
import hatImg from "./Images/hat.png"
import islandImg from "./Images/island.png"
import jarImg from "./Images/jar.png"
import keyImg from "./Images/key.png"
import leafImg from "./Images/leaf.png"
import moonImg from "./Images/moon.png"
import needleImg from "./Images/needle.png"
import owlImg from "./Images/owl.png"
import pantsImg from "./Images/pants.png"
import queenImg from "./Images/queen.png"
import rocksImg from "./Images/rocks.png"
import sunImg from "./Images/sun.png"
import tomatoImg from "./Images/tomato.png"
import unicycleImg from "./Images/unicycle.png"
import violinImg from "./Images/violin.png"
import waterImg from "./Images/water.png"
import xrayImg from "./Images/xray.png"
import yellowImg from "./Images/yellow.png"
import zebraImg from "./Images/zebra.png"

import antImg from "./Images/ant.png"
import ballImg from "./Images/ball.png"
import carImg from "./Images/car.png"
import duckImg from "./Images/duck.png"
import emailImg from "./Images/email.png"
import frogImg from "./Images/frog.png"
import goatImg from "./Images/goat.png"
import homeImg from "./Images/home.png"
import iceImg from "./Images/ice.png"
import jetImg from "./Images/jet.png"
import kiteImg from "./Images/kite.png"
import ladderImg from "./Images/ladder.png"
import monkeyImg from "./Images/monkey.png"
import nutImg from "./Images/nut.png"
import octopusImg from "./Images/octopus.png"
import pigImg from "./Images/pig.png"
import quietImg from "./Images/quiet.png"
import rabbitImg from "./Images/rabbit.png"
import snakeImg from "./Images/snake.png"
import truckImg from "./Images/truck.png"
import unicornImg from "./Images/unicorn.png"
import vacuumImg from "./Images/vacuum.png"
import wormImg from "./Images/worm.png"
import xylophoneImg from "./Images/xylophone.png"
//import yoyoImg from "./Images/yoyo.png"
//import zooImg from "./Images/zoo.png"

import astronautImg from "./Images/astronaut.png"
import bearImg from "./Images/bear.png"
import cakeImg from "./Images/cake.png"
import drumImg from "./Images/drum.png"
import eatImg from "./Images/eat.png"
import fishImg from "./Images/fish.png"
import grapesImg from "./Images/grapes.png"
import handImg from "./Images/hand.png"
import iglooImg from "./Images/igloo.png"
import jacketImg from "./Images/jacket.png"
import kickImg from "./Images/kick.png"
import lemonImg from "./Images/lemon.png"
import milkImg from "./Images/milk.png"
import nestImg from "./Images/nest.png"
import orangeImg from "./Images/orange.png"
import pumpkinImg from "./Images/pumpkin.png"
//import quiltImg from "./Images/quilt.png"
import rainImg from "./Images/rain.png"
import starImg from "./Images/star.png"
import turtleImg from "./Images/turtle.png"
import umbrellaImg from "./Images/umbrella.png"
import vanImg from "./Images/van.png"
import whaleImg from "./Images/whale.png"
import foxImg from "./Images/fox.png"
//import yarnImg from "./Images/yarn.png"
import zipperImg from "./Images/zipper.png"

//////////////////////////////////////////////////////////
/////////////////Import all sounds////////////////////////
//////////////////////////////////////////////////////////
import appleSnd from "./WordSound/apple.flac"
import booksSnd from "./WordSound/books.flac"
import catSnd from "./WordSound/cat.flac"
import dogSnd from "./WordSound/dog.flac"
import eggsSnd from "./WordSound/eggs.flac"
import flowerSnd from "./WordSound/flower.flac"
import giftSnd from "./WordSound/gift.flac"
import hatSnd from "./WordSound/hat.flac"
import islandSnd from "./WordSound/island.flac"
import jarSnd from "./WordSound/jar.flac"
import keySnd from "./WordSound/key.flac"
import leafSnd from "./WordSound/leaf.flac"
import moonSnd from "./WordSound/moon.flac"
import needleSnd from "./WordSound/needle.flac"
import owlSnd from "./WordSound/owl.flac"
import pantsSnd from "./WordSound/pants.flac"
import queenSnd from "./WordSound/queen.flac"
import rocksSnd from "./WordSound/rocks.flac"
import sunSnd from "./WordSound/sun.flac"
import tomatoSnd from "./WordSound/tomato.flac"
import unicycleSnd from "./WordSound/unicycle.flac"
import violinSnd from "./WordSound/violin.flac"
import waterSnd from "./WordSound/water.flac"
import xraySnd from "./WordSound/xray.flac"
import yellowSnd from "./WordSound/yellow.flac"
import zebraSnd from "./WordSound/zebra.flac"

import astronautSnd from "./WordSound/astronaut.mp3"
import bearSnd from "./WordSound/bear.mp3"
import cakeSnd from "./WordSound/cake.mp3"
import drumSnd from "./WordSound/drum.mp3"
import eatSnd from "./WordSound/eat.mp3"
import fishSnd from "./WordSound/fish.mp3"
import grapesSnd from "./WordSound/grape.mp3"
import handSnd from "./WordSound/hand.mp3"
import iglooSnd from "./WordSound/igloo.mp3"
import jacketSnd from "./WordSound/jacket.mp3"
import kickSnd from "./WordSound/kick.mp3"
import lemonSnd from "./WordSound/lemon.mp3"
import milkSnd from "./WordSound/milk.mp3"
import nutSnd from "./WordSound/nut.mp3"
import orangeSnd from "./WordSound/orange.mp3"
import pumpkinSnd from "./WordSound/pumpkin.mp3"
import quiltSnd from "./WordSound/quilt.mp3"
import rainSnd from "./WordSound/rain.mp3"
import starSnd from "./WordSound/star.mp3"
import turtleSnd from "./WordSound/turtle.mp3"
import umbrellaSnd from "./WordSound/umbrella.mp3"
import vanSnd from "./WordSound/van.mp3"
import whaleSnd from "./WordSound/whale.mp3"
import foxSnd from "./WordSound/fox.mp3"
import yarnSnd from "./WordSound/yarn.mp3"
import zipperSnd from "./WordSound/zipper.mp3"

import antSnd from "./WordSound/ant.wav"
import ballSnd from "./WordSound/ball.mp3"
import carSnd from "./WordSound/car.mp3"
import duckSnd from "./WordSound/duck.mp3"
//import earthSnd from "./WordSound/earth.mp3"
import frogSnd from "./WordSound/frog.mp3"
import goatSnd from "./WordSound/goat.mp3"
import homeSnd from "./WordSound/home.mp3"
import iceSnd from "./WordSound/ice.mp3"
import jetSnd from "./WordSound/jet.mp3"
import kiteSnd from "./WordSound/kite.mp3"
import ladderSnd from "./WordSound/ladder.mp3"
import monkeySnd from "./WordSound/monkey.mp3"
import nestSnd from "./WordSound/nest.mp3"
import octopusSnd from "./WordSound/octopus.mp3"
import pigSnd from "./WordSound/pig.mp3"
import quietSnd from "./WordSound/quiet.mp3"
import rabbitSnd from "./WordSound/rabbit.mp3"
import snakeSnd from "./WordSound/snake.mp3"
import truckSnd from "./WordSound/truck.flac"
import unicornSnd from "./WordSound/unicorn.mp3"
import vacuumSnd from "./WordSound/vacuum.mp3"
import wormSnd from "./WordSound/worm.mp3"
import xylophoneSnd from "./WordSound/xylophone.mp3"
//import yoyoSnd from "./WordSound/yoyo.mp3"
import zooSnd from "./WordSound/zoo.mp3"

//data to use for learn words
const gameData = [
    {word: "A", imgSrc: appleImg, soundSrc: appleSnd},
    {word: "E", imgSrc: moonImg, soundSrc: moonSnd},
    {word: "N", imgSrc: owlImg, soundSrc: owlSnd},
    {word: "T", imgSrc: truckImg, soundSrc: truckSnd},
 
]

export default gameData